#pragma once

#define DISTRHO_PLUGIN_NAME        "5yn7h_"
#define DISTRHO_PLUGIN_URI         "https://github.com/yourname/5yn7h_"
#define DISTRHO_PLUGIN_CLAP_ID     "com.yourname.5yn7h_"
#define DISTRHO_PLUGIN_BRAND       "5yn7h_"
#define DISTRHO_PLUGIN_VERSION     d_version(1,0,0)
#define DISTRHO_PLUGIN_UNIQUE_ID   0x53594E37
#define DISTRHO_PLUGIN_DESCRIPTION "Modern multi-engine synth inspired by Plaits/Peaks"
#define DISTRHO_PLUGIN_MAKER       "PatF"
#define DISTRHO_PLUGIN_LICENSE     "MIT"
#define DISTRHO_PLUGIN_IS_SYNTH    1
#define DISTRHO_PLUGIN_NUM_INPUTS  0
#define DISTRHO_PLUGIN_NUM_OUTPUTS 2
#define DISTRHO_PLUGIN_WANT_MIDI_INPUT 1
#define DISTRHO_PLUGIN_WANT_MIDI_OUTPUT 0
#define DISTRHO_PLUGIN_WANT_STATE  0
#define DISTRHO_PLUGIN_WANT_PROGRAMS 0
#define DISTRHO_PLUGIN_WANT_TIMEPOS 0
#define DISTRHO_PLUGIN_WANT_LATENCY 0
#define DISTRHO_PLUGIN_WANT_DIRECT_ACCESS 0
#define DISTRHO_PLUGIN_WANT_ALL_PARAM_VALUES 0
#define DISTRHO_PLUGIN_WANT_PARAMETER_VALUE_CHANGE_REQUEST 0
#define DISTRHO_PLUGIN_WANT_CALLBACKS 0
#define DISTRHO_PLUGIN_WANT_EXTRA 0
